version = 1

test_patterns = ["/tests/**", "/cypress/**"]

exclude_patterns = [
  "/.github/**",
  "/public",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
